apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec: 
  type: NodePort
  selector:
     app.kubernetes.io/name: grafana
  ports:
     - port: 80
       targetPort: 3000
       nodePort: 30080 
