apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: traefik
  creationTimestamp: "2022-01-09T05:52:45Z"
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-10.9.1
  name: traefik
  namespace: traefik
  resourceVersion: "15482199"
  uid: bbe3dafc-0683-46ad-a996-1ad747bff3f4
spec:
  clusterIP: 10.104.81.148
  clusterIPs:
  - 10.104.81.148
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    nodePort: 30780
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    nodePort: 30948
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
