apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: personal-website
  namespace: flux-system
spec:
  secretRef:
    name: ecr-credentials
  image: 573500965530.dkr.ecr.us-east-2.amazonaws.com/personalwebsite
  interval: 1m0s