apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: personal-website
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: personal-website
  policy:
    numerical:
      order: asc